# This file was generated by GoReleaser. DO NOT EDIT.
class Poly < Formula
  desc "A command line utility for engineering organisms."
  homepage "https://github.com/TimothyStiles/poly"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/timothystiles/poly/releases/download/v0.5.0/poly_0.5.0_Darwin_x86_64.tar.gz"
    sha256 "762d9c250b45ade8e4708b90256f49bb491db89dfae57f58a20f552477e7febc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/timothystiles/poly/releases/download/v0.5.0/poly_0.5.0_Linux_x86_64.tar.gz"
      sha256 "8b0b13f7c5575d999daf3a620d88eb195edd7a85735ed082270e84d6c15b12a5"
    end
  end
  
  depends_on "go"

  def install
    bin.install "poly"
  end

  test do
    system "#{bin}/poly -h"
  end
end
