# This file was generated by GoReleaser. DO NOT EDIT.
class Poly < Formula
  desc "A command line utility for engineering organisms."
  homepage "https://github.com/TimothyStiles/poly"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/timothystiles/poly/releases/download/v0.2.0/poly_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "5fdf1b432a2bfbf1c638a86b1ce75d2e67af79d44276ec7d8bc9022c81bddfad"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/timothystiles/poly/releases/download/v0.2.0/poly_0.2.0_Linux_x86_64.tar.gz"
      sha256 "dcd0533e08b54fd2c134264ce20f3c6c433b03e745d6e2a5f54a3360e55684e3"
    end
  end
  
  depends_on "go"

  def install
    bin.install "poly"
  end

  test do
    system "#{bin}/poly -h"
  end
end
